spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8093
  mail:
    host: smtp.gmail.com
    port: 587
    username: kadent.group.communication@gmail.com
    password: (a+b)==(b+a);
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true