spring:
  datasource:
    url: jdbc:mysql://db:3306/kadent_db
    username: kadent
    password: t@keYourM3dicin3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://db:3306/kadent_db
    user: kadent
    password: t@keYourM3dicin3
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 84e2ca001@smtp-brevo.com
    password: R8BAKQHJMpIT9gXC
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  devtools:
    restart:
      enabled: true
      additional-paths: target/classes
server:
  port: 8093

logging:
  level:
    org.flywaydb: debug