spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cabinet_medicale_multi_post
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8093