spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 84e2ca001@smtp-brevo.com
    password: R8BAKQHJMpIT9gXC
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
server:
  port: 8093